"""empty message

Revision ID: cb53aa3bf530
Revises: 16e1056981ef
Create Date: 2024-06-15 14:47:36.974420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb53aa3bf530'
down_revision: Union[str, None] = '16e1056981ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('newsletters', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('content', sa.VARCHAR(), nullable=False))
    op.drop_column('newsletters', 'name')
    # ### end Alembic commands ###
